// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20241115225434_AddBookSeedData")]
    partial class AddBookSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "İtaatsizlik Üzerine"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Sevme Sanatı"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Yas ve Melankoli"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Ego ve Id"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Totem ve Tabu"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Uygarlığın Huzursuzluğu"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Dört Arketip"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Yaşama Sanatı"
                        },
                        new
                        {
                            Id = 9,
                            Title = "Kitle Psikolojisi"
                        },
                        new
                        {
                            Id = 10,
                            Title = "Rüyaların Yorumu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
